/**
 * A local copy of Meta's Template Library catalog, extracted directly
 * from WhatsApp Manager's own internal GraphQL API response (captured
 * via a browser HAR export from a real, logged-in WhatsApp Manager
 * session — this data is not reachable through Meta's public/
 * documented Graph API, which returns an empty result set for real
 * WABAs; see meta-api.ts for the full investigation).
 *
 * Every entry's `name` is the exact `library_template_name` Meta
 * expects when creating a template from this catalog
 * (POST /<WABA_ID>/message_templates) — that call IS on the public,
 * documented, working Graph API, so browsing happens against this
 * local snapshot while creation still goes to Meta live.
 *
 * This snapshot will drift from Meta's actual live catalog over time
 * (new templates added, existing ones changed) since it isn't
 * re-fetched automatically. Re-capture periodically by repeating the
 * HAR-export process against WhatsApp Manager's Template Library page.
 */

export interface CatalogButton {
  type: string
  text: string
  url?: string
  phoneNumber?: string
}

export interface TemplateLibraryCatalogEntry {
  name: string
  category: 'UTILITY' | 'AUTHENTICATION'
  topic: string
  usecase: string
  industries: string[]
  language: string
  header?: string
  body: string
  footer?: string
  buttons?: CatalogButton[]
}

export const TEMPLATE_LIBRARY_CATALOG: TemplateLibraryCatalogEntry[] = [
  {
    name: "delivery_code_1",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "IN_PERSON_VERIFICATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Your order is arriving soon. *{{1}}* is your verification code. Please show this to the delivery associate.",
  },
  {
    name: "delivery_code_2",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "IN_PERSON_VERIFICATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}},\n\nYour {{2}} order is currently pending shipment. The estimated delivery date is {{3}}, with delivery scheduled between {{4}} and {{5}}.\n\nPlease note, the delivery person may ask for your delivery code {{6}} upon arrival.",
  },
  {
    name: "delivery_code_3",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "IN_PERSON_VERIFICATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Your order is on its way and scheduled to arrive at {{1}}.  Please show verification code *{{2}}* to receive your order.",
  },
  {
    name: "delivery_code_4",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "IN_PERSON_VERIFICATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Please share code *{{1}}* with delivery agent after verifying the package.",
  },
  {
    name: "delivery_code_5",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "IN_PERSON_VERIFICATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Your order of {{1}} items (Order ID: {{2}}) is out for delivery today.\n\nPlease provide the code *{{3}}* to the delivery agent to receive your order.",
  },
  {
    name: "delivery_code_6",
    category: "AUTHENTICATION",
    topic: "PAYMENTS",
    usecase: "IN_PERSON_VERIFICATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Your order {{1}} is on its way and scheduled to arrive {{2}}. Please show verification code {{3}} to receive your order.",
  },
  {
    name: "in_person_banking_user_verification",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "IN_PERSON_VERIFICATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Your personal data will be updated, provide the account executive with the verification code: {{1}}",
  },
  {
    name: "login_code",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_USER",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Your login code is {{1}}. No further action is needed if you didn’t request this.",
  },
  {
    name: "temporary_password",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_USER",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Your temporary password is {{1}}. Please log in and update it as soon as possible.",
  },
  {
    name: "verify_account",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_USER",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES", "TELECOMMUNICATION"],
    language: "en_US",
    body: "This OTP code is for {{1}} your {{2}} account and linking it to {{3}}. \nOTP: {{4}}\nDo not share it with anyone, even to {{5}}, or they'll be able to access your account. ",
  },
  {
    name: "verify_account_2",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_USER",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES", "TELECOMMUNICATION"],
    language: "en_US",
    body: "This code is for {{1}} your {{2}} account and linking it to {{3}}. Code: {{4}}\nDo not share it. ",
  },
  {
    name: "verify_code",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_USER",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES", "TELECOMMUNICATION"],
    language: "en_US",
    body: "OTP Code: {{1}}. This is your OTP for {{2}}. The OTP is valid for {{3}}. Call {{4}} if you did not perform this request.",
  },
  {
    name: "verify_code_1",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_USER",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES"],
    language: "en_US",
    body: "*{{1}}* is your verification code.",
  },
  {
    name: "verify_otp_usecase",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_TRANSACTION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "OTP Code: {{1}}. This is your OTP code for {{2}}. For your security, do not share this code.",
  },
  {
    name: "verify_password_recovery",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_USER",
    industries: ["FINANCIAL_SERVICES", "E_COMMERCE"],
    language: "en_US",
    body: "*{{1}}* is your password recovery code.",
  },
  {
    name: "verify_transaction_1",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_TRANSACTION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Use code *{{1}}* to authorize your transaction.",
  },
  {
    name: "verify_transaction_2",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_TRANSACTION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Use code *{{1}}* to verify your transaction of {{2}}. If you did not request this transaction, please contact support.",
  },
  {
    name: "verify_transaction_3",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_TRANSACTION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Use code *{{1}}* to verify your transaction of {{2}} on your card ending in {{3}}. If you did not request this transaction, please contact support.",
  },
  {
    name: "verify_transaction_4",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_TRANSACTION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Use code *{{1}}* to verify your transaction of {{2}} on your account ending in {{3}}.  Thank you!",
  },
  {
    name: "verify_transfer_1",
    category: "AUTHENTICATION",
    topic: "IDENTITY_VERIFICATION",
    usecase: "VERIFY_TRANSACTION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Your verification code is *{{1}}* for the transfer of {{2}}. Please use this code to complete your transaction.",
  },
  {
    name: "account_creation_confirmation_3",
    category: "UTILITY",
    topic: "ACCOUNT_UPDATES",
    usecase: "ACCOUNT_CREATION_CONFIRMATION",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Finalize account set-up",
    body: "Hi {{1}},\n\nYour new account has been created successfully. \n\nPlease verify {{2}} to complete your profile.",
    buttons: [
      { type: "URL", text: "Verify account", url: "https://www.example.com" },
    ],
  },
  {
    name: "address_update",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_UPDATE",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Address update",
    body: "Hi {{1}}, your delivery address has been successfully updated to {{2}}. Contact {{3}} for any inquiries.",
  },
  {
    name: "appointment_cancellation_1",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_CANCELLATION",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES", "TELECOMMUNICATION"],
    language: "en_US",
    header: "Your appointment was canceled",
    body: "Hello {{1}},\n\nYour upcoming appointment with {{2}} on {{3}} at {{4}} has been canceled.\n\nLet us know if you have any questions or need to reschedule.\n\n",
    buttons: [
      { type: "URL", text: "View details", url: "https://www.example.com" },
    ],
  },
  {
    name: "appointment_cancelled",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_CANCELLATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Appointment cancelled",
    body: "Hi {{1}},\nYour appointment on {{2}} has been cancelled. We hope to see you another time.\n",
  },
  {
    name: "appointment_confirmation_1",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_CONFIRMATION",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES", "TELECOMMUNICATION"],
    language: "en_US",
    header: "Your appointment is booked",
    body: "Hello {{1}},\n\nThank you for booking with {{2}}.\n\nYour appointment for {{3}} on {{4}} at {{5}} is confirmed.\n",
    buttons: [
      { type: "URL", text: "View details", url: "https://www.example.com" },
    ],
  },
  {
    name: "appointment_confirmed",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Appointment confirmed",
    body: "Hi {{1}},\nYour appointment is scheduled for {{2}}.\n\nService: {{3}}\nConfirmation number: {{4}}\n\nWe're looking forward to your visit.\n\n",
  },
  {
    name: "appointment_reminder",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_REMINDER",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Reminder: Our technician will visit your location on {{1}} at {{2}} for your broadband installation. Please be available.",
  },
  {
    name: "appointment_reminder_2",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_REMINDER",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES", "TELECOMMUNICATION"],
    language: "en_US",
    header: "You have an upcoming appointment",
    body: "Hello {{1}},\n\nThis is a reminder about your upcoming appointment with {{2}} on {{3}} at {{4}}.\n\nWe look forward to seeing you!\n",
    buttons: [
      { type: "URL", text: "View details", url: "https://www.example.com" },
    ],
  },
  {
    name: "appointment_reschedule_1",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_SCHEDULEING",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES", "TELECOMMUNICATION"],
    language: "en_US",
    header: "Your appointment was rescheduled",
    body: "Hello {{1}},\n\nYour upcoming appointment with {{2}} has been rescheduled for {{3}} at {{4}}. \n\nWe look forward to seeing you!\n",
    buttons: [
      { type: "URL", text: "View details", url: "https://www.example.com" },
    ],
  },
  {
    name: "appointment_rescheduled",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_SCHEDULEING",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Appointment rescheduled",
    body: "Hi {{1}},\nYour appointment has been rescheduled to {{2}}.\n\nService: {{3}}\nConfirmation number: {{4}}\n\nWe're looking forward to your visit.\n",
  },
  {
    name: "appointment_scheduling",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_SCHEDULEING",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Technician visit",
    body: "Hi {{1}}, we're scheduling a technician visit for your {{2}} on {{3}} between {{4}} and {{5}}. Please confirm if this time slot works for you.",
    buttons: [
      { type: "QUICK_REPLY", text: "Confirm" },
      { type: "QUICK_REPLY", text: "Reschedule" },
    ],
  },
  {
    name: "appointment_scheduling_address",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_SCHEDULEING",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Technician visit",
    body: "Hi {{1}}, we're scheduling a technician visit to {{2}} on {{3}} between {{4}} and {{5}}. Please confirm if this time slot works for you.",
    buttons: [
      { type: "QUICK_REPLY", text: "Confirm" },
      { type: "QUICK_REPLY", text: "Reschedule" },
    ],
  },
  {
    name: "auto_pay_reminder_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "AUTO_PAY_REMINDER",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Upcoming automatic payment",
    body: "Hi {{1}}, \n\nYour automatic payment for {{2}} is scheduled on {{3}} for {{4}}.\n\nKindly ensure your balance is sufficient to avoid {{5}} fees.",
    buttons: [
      { type: "URL", text: "View account", url: "https://www.example.com" },
    ],
  },
  {
    name: "auto_pay_reminder_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "AUTO_PAY_REMINDER",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Upcoming automatic payment",
    body: "Hi {{1}}, this is to remind you of your upcoming auto-pay: \n\nDate: {{2}}\nAccount: {{3}}\nAmount: {{4}}\n\nThank you and have a nice day.",
    buttons: [
      { type: "URL", text: "View details", url: "https://www.example.com" },
    ],
  },
  {
    name: "auto_pay_reminder_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "AUTO_PAY_REMINDER",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Reminder: \n\nYour scheduled payment for your {{1}} card ending in {{2}} is scheduled for {{3}}. \n\nThank you.",
  },
  {
    name: "call_permission_request_1",
    category: "UTILITY",
    topic: "CALL_PERMISSIONS",
    usecase: "CALL_PERMISSION_REQUEST",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Would you like to receive a call from one of our representatives?",
  },
  {
    name: "cancellation_confirmation",
    category: "UTILITY",
    topic: "ACCOUNT_UPDATES",
    usecase: "CANCELLATION_CONFIRMATION",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, we've received a cancellation request for your {{2}}. Reply with YES to be assigned a new agent or NO to cancel.",
    buttons: [
      { type: "QUICK_REPLY", text: "Yes" },
      { type: "QUICK_REPLY", text: "No" },
    ],
  },
  {
    name: "card_transaction_alert_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "TRANSACTION_ALERT",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "This is to notify you that your {{1}} card ending in {{2}} was charged {{3}} by {{4}}.",
  },
  {
    name: "card_transaction_alert_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "TRANSACTION_ALERT",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Thank you for using your {{1}} card. This confirms your purchase on {{2}} for {{3}} at {{4}}.",
  },
  {
    name: "crisis_response_1",
    category: "UTILITY",
    topic: "PUBLIC_SAFETY",
    usecase: "CRISIS_RESPONSE",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "We activated support services for the {{1}} in the {{2}} area. Please take the following precautions if you live in {{3}} or surrounding areas: {{4}}, {{5}}, {{6}}.",
  },
  {
    name: "crisis_response_2",
    category: "UTILITY",
    topic: "PUBLIC_SAFETY",
    usecase: "CRISIS_RESPONSE",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "There is an active {{1}} in the {{2}} area. For live updates on the {{3}} alert in the {{4}} area, visit our website {{5}}.",
  },
  {
    name: "delivery_confirmation_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}}, your order {{2}} was delivered successfully. \n\nYou can manage your order below. \n",
    buttons: [
      { type: "URL", text: "Manage order", url: "https://www.example.com" },
    ],
  },
  {
    name: "delivery_confirmation_2",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order delivered",
    body: "Hi {{1}}, your order {{2}} was delivered. \n\nNeed to return or replace an item?\nClick to manage your order.\n",
    buttons: [
      { type: "URL", text: "Manage order", url: "https://www.example.com" },
    ],
  },
  {
    name: "delivery_confirmation_3",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "{{1}}, your order {{2}} was delivered on {{3}}.\n\nIf you need to return or replace item(s), please click below.",
    buttons: [
      { type: "URL", text: "Start return", url: "https://www.example.com" },
    ],
  },
  {
    name: "delivery_confirmation_4",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "{{1}}, your order was successfully delivered on {{2}}.\n\nThank you for your purchase.\n",
  },
  {
    name: "delivery_confirmation_5",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order delivered",
    body: "Hi {{1}},\n\nGreat news! Your order {{2}} was delivered.",
    buttons: [
      { type: "URL", text: "View order", url: "https://www.example.com" },
    ],
  },
  {
    name: "delivery_failed_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_FAILED",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Could not deliver your order",
    body: "Hi {{1}}, \n\nWe attempted to deliver your order on {{2}} but were not successful. \n\nPlease contact us at {{3}} to arrange re-delivery. \n\nThank you.",
    buttons: [
      { type: "URL", text: "Manage delivery", url: "https://www.example.com" },
      { type: "PHONE_NUMBER", text: "Call us", phoneNumber: "+18005551234" },
    ],
  },
  {
    name: "delivery_failed_2",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_FAILED",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "We were unable to deliver order {{1}} today. \n\nPlease {{2}} to schedule another delivery attempt.",
    buttons: [
      { type: "URL", text: "Schedule delivery", url: "https://www.example.com" },
    ],
  },
  {
    name: "delivery_update_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_UPDATE",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}}, your order {{2}} is on its way and should arrive soon.\n\nEstimated delivery:  {{3}}\n\nWe will provide an update when your order is delivered.",
    footer: "An adult must be home to accept this package.",
    buttons: [
      { type: "URL", text: "Track order", url: "https://www.example.com" },
    ],
  },
  {
    name: "delivery_update_2",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_UPDATE",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}}, our order {{2}} is out for delivery! \n\nIt should be delivered {{3}} between {{4}} and {{5}}.\n",
    buttons: [
      { type: "URL", text: "Track order", url: "https://www.example.com" },
    ],
  },
  {
    name: "delivery_update_3",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_UPDATE",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Your order {{1}} is out for delivery! \n\nIt should arrive by {{2}}. \n\nThank you for your business.",
    buttons: [
      { type: "URL", text: "Track order", url: "https://www.example.com" },
    ],
  },
  {
    name: "delivery_update_4",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_UPDATE",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Your order {{1}} is out for delivery and is expected to arrive by {{2}}.\n\nThank you for your business.",
  },
  {
    name: "device_recovery",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "RETURN_CONFIRMATION",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Device return",
    body: "Hi {{1}}, your broadband connection has been disconnected. To return your device, please follow these steps: \n{{2}} \nYou can also contact us at {{3}} for assistance.",
  },
  {
    name: "disbursement_balance_1",
    category: "UTILITY",
    topic: "PUBLIC_SERVICE",
    usecase: "DISBURSEMENTS",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Your {{1}} disbursement balance is {{2}}. Kindly note it will expire on {{3}}. New {{4}} disbursements will be announced on a monthly basis. Use the URL below to review the disbursement schedule and to register or change your enrollment status.",
    buttons: [
      { type: "URL", text: "View Schedule", url: "https://example.gov/disbursement-schedule" },
    ],
  },
  {
    name: "disbursement_voucher_1",
    category: "UTILITY",
    topic: "PUBLIC_SERVICE",
    usecase: "DISBURSEMENTS",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "{{1}} vouchers are here! You are eligible to claim your voucher at {{2}} or online via our website {{3}}. Vouchers are valid until {{4}}. Vouchers can be used at many locations. Refer to our website {{5}} for a comprehensive list of all locations that accept vouchers.",
  },
  {
    name: "event_details_reminder_1",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "EVENT_DETAILS_REMINDER",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES"],
    language: "en_US",
    header: "You have an upcoming event",
    body: "You have an upcoming event\nReminder: You RSVP’ed to {{1}} by {{2}}.\n\nThe event starts on {{3}} at {{4}} at {{5}} location.",
  },
  {
    name: "event_details_reminder_2",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "EVENT_DETAILS_REMINDER",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Reminder: {{1}} is coming up and you have RSVP’ed to this event by {{2}}. \n\nSee you at {{3}} at {{4}} local time.\n",
  },
  {
    name: "event_rsvp_confirmation_1",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "EVENT_RSVP_CONFIRMATON",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Thank you for RSVP’ing to {{1}} by {{2}}. \n\nSee you on {{3}} at {{4}} local time.\n",
  },
  {
    name: "event_rsvp_confirmation_2",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "EVENT_RSVP_CONFIRMATON",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Your RSVP for {{1}} by {{2}} is confirmed!\n\nThanks!",
  },
  {
    name: "feedback_collection",
    category: "UTILITY",
    topic: "CUSTOMER_FEEDBACK",
    usecase: "FEEDBACK_SURVEY",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, the service request we completed on {{2}} is now closed. Please rate your experience from 1-5 and share any feedback to help us improve.",
  },
  {
    name: "feedback_survey_1",
    category: "UTILITY",
    topic: "CUSTOMER_FEEDBACK",
    usecase: "FEEDBACK_SURVEY",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Hi {{1}},\n\nThank you for your recent {{2}} on {{3}}.\n\nWe value your feedback and would appreciate you sharing more about your experience with us at the link below.\n\nThis should only take {{4}} minutes. We appreciate your time.",
    buttons: [
      { type: "URL", text: "Leave feedback", url: "https://www.example.com" },
    ],
  },
  {
    name: "feedback_survey_2",
    category: "UTILITY",
    topic: "CUSTOMER_FEEDBACK",
    usecase: "FEEDBACK_SURVEY",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES"],
    language: "en_US",
    header: "How did we do?",
    body: "Thank you for visiting us at {{1}} on {{2}}. \n\nWe value your feedback.\n\nPlease fill out this short survey to let us know how we can continue to improve.",
    buttons: [
      { type: "URL", text: "Fill out survey", url: "https://www.example.com" },
    ],
  },
  {
    name: "followup_missed_calls",
    category: "UTILITY",
    topic: "CUSTOMER_FEEDBACK",
    usecase: "FOLLOW_UP_MISSED_CALLS",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Missed call",
    body: "Hi {{1}}, we missed your call. Please let us know if you're available to reschedule.",
    buttons: [
      { type: "QUICK_REPLY", text: "Reschedule Call" },
    ],
  },
  {
    name: "fraud_alert_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "FRAUD_ALERT",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Hello {{1}},\n\nWe noticed a {{2}} transaction on your {{3}} from {{4}} for {{5}}.\n\nIf you didn't make this transaction, please call us {{6}} at {{7}}. \n\nYou can also click below to freeze your {{8}}.\n\nThank you!",
    buttons: [
      { type: "PHONE_NUMBER", text: "Call us", phoneNumber: "+18005551234" },
      { type: "URL", text: "Freeze card", url: "https://www.example.com" },
    ],
  },
  {
    name: "fraud_alert_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "FRAUD_ALERT",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Hi {{1}},\n\nThis is {{2}}.\n\nWe identified a {{3}} transaction on your {{4}} card ending in {{5}}:\n\nDate: {{6}}\nMerchant: {{7}}\nAmount: {{8}}\n\nDid you make this purchase?\n",
    buttons: [
      { type: "QUICK_REPLY", text: "Yes" },
      { type: "QUICK_REPLY", text: "No" },
    ],
  },
  {
    name: "fraud_alert_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "FRAUD_ALERT",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Hi {{1}},\n\nWe noticed a {{2}} charge on your {{3}} account. \n\nPlease verify the details of this transaction.",
    buttons: [
      { type: "URL", text: "Verify transaction", url: "https://www.example.com" },
    ],
  },
  {
    name: "fraud_alert_4",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "FRAUD_ALERT",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Suspicious transaction",
    body: "Hello {{1}},\n\nWe detected a suspicious transaction on your {{2}} card ending in {{3}}.\n\nPlease verify if this was you.",
    buttons: [
      { type: "URL", text: "Verify transaction", url: "https://www.example.com" },
    ],
  },
  {
    name: "fraud_awareness_1",
    category: "UTILITY",
    topic: "ACCOUNT_OR_PRODUCT_PROTECTION",
    usecase: "FRAUD_AWARENESS",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "We have detected an increase in {{1}}. To protect your card ending in {{2}}, please consider updating your PIN. Click below to see the step-by-step. Do not click on unofficial links. {{3}} will never send you SMS messages asking for your personal information or banking details.",
    buttons: [
      { type: "URL", text: "Security Guide", url: "https://example.com/security-guide" },
    ],
  },
  {
    name: "group_invite_link",
    category: "UTILITY",
    topic: "GROUP_INVITE_LINK",
    usecase: "GROUP_INVITE_UPON_REQUEST",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}}, your request for {{2}} service from {{3}} was successfully received!\n\nYou can start the service by clicking and joining the group below.\n{{4}}\n\nThank you!",
  },
  {
    name: "group_invite_link_concise",
    category: "UTILITY",
    topic: "GROUP_INVITE_LINK",
    usecase: "GROUP_INVITE_UPON_REQUEST",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Your {{1}} request with {{2}} is confirmed. Please join the WhatsApp group to start:\n{{3}} Thank you!",
  },
  {
    name: "group_invite_link_detailed",
    category: "UTILITY",
    topic: "GROUP_INVITE_LINK",
    usecase: "GROUP_INVITE_UPON_REQUEST",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}},\nWe are pleased to inform you that your request for {{2}} from {{3}} has been successfully received.\n\nTo facilitate your session, we have created a dedicated WhatsApp group. Please join the group using the link below to proceed with your request:\n{{4}}\n\nThank you for using our service!",
  },
  {
    name: "health_awareness_1",
    category: "UTILITY",
    topic: "PUBLIC_SERVICE",
    usecase: "HEALTH_AWARENESS",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Stay up-to-date with your health. Stop by {{1}} by {{2}} to get your free {{3}}. Bring your {{4}} and {{5}}.",
  },
  {
    name: "health_emergency_1",
    category: "UTILITY",
    topic: "PUBLIC_SERVICE",
    usecase: "HEALTH_EMERGENCY",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "The {{1}} has just declared a health emergency due to {{2}}. To learn more about {{3}} and precautions to take, use the URL below. We will follow up with more details once available.",
    buttons: [
      { type: "URL", text: "Learn More", url: "https://example.gov/health-emergency/{{1}}" },
    ],
  },
  {
    name: "health_emergency_2",
    category: "UTILITY",
    topic: "PUBLIC_SERVICE",
    usecase: "HEALTH_EMERGENCY",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "A health emergency due to {{1}} has been declared in the {{2}} area. Live updates available on our website {{3}}.",
  },
  {
    name: "identity_compliance_1",
    category: "UTILITY",
    topic: "LEGAL_REGULATORY_COMPLIANCE",
    usecase: "IDENTITY_COMPLIANCE",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "This is to notify you that you need to upgrade to a {{1}} by {{2}}. To avoid any inconveniences when travelling, please ensure you make an appointment at your local {{3}}. To find the office closest to you, use our website {{4}}.",
  },
  {
    name: "identity_compliance_2",
    category: "UTILITY",
    topic: "LEGAL_REGULATORY_COMPLIANCE",
    usecase: "IDENTITY_COMPLIANCE",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Upgraded {{1}} are now required when traveling at airports. For more information on how to upgrade, use the link below.",
    buttons: [
      { type: "URL", text: "Learn More", url: "https://example.gov/id-upgrade" },
    ],
  },
  {
    name: "installation_complete",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Installation complete",
    body: "Hi {{1}}, your {{2}} installation is complete! Our technician has configured your connection, and you're now ready to go online. If you have any issues, feel free to reply or contact {{3}} for assistance.",
  },
  {
    name: "low_balance_warning_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "LOW_BALANCE_WARNING",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Low account balance",
    body: "Hi {{1}}, \n\nThis is to notify you that your {{2}} in your {{3}} account ending in {{4}} is below your pre-set {{5}} of {{6}}. \n\nClick below to add funds or call us.",
    buttons: [
      { type: "URL", text: "Make a deposit", url: "https://www.example.com" },
      { type: "PHONE_NUMBER", text: "Call us", phoneNumber: "+18005551234" },
    ],
  },
  {
    name: "low_balance_warning_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "LOW_BALANCE_WARNING",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Hi {{1}}, \n\nAvailable funds in your {{2}} account ending in {{3}} are below your pre-set {{4}} limit.",
    buttons: [
      { type: "URL", text: "Make a deposit", url: "https://www.example.com" },
      { type: "PHONE_NUMBER", text: "Call us", phoneNumber: "+18005551234" },
    ],
  },
  {
    name: "low_balance_warning_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "LOW_BALANCE_WARNING",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Low balance notification",
    body: "Hi {{1}}, your mobile balance is {{2}}. Please recharge to avoid interruption. ",
    buttons: [
      { type: "URL", text: "Recharge", url: "https://www.example.com" },
    ],
  },
  {
    name: "missed_appointment",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "APPOINTMENT_MISSED",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Missed visit",
    body: "Hi {{1}}, we missed you at your scheduled {{2}} appointment on {{3}}. Please reply to reschedule or contact {{4}} to book a new appointment.",
    buttons: [
      { type: "QUICK_REPLY", text: "Reschedule" },
    ],
  },
  {
    name: "network_troubleshooting",
    category: "UTILITY",
    topic: "ACCOUNT_UPDATES",
    usecase: "NETWORK_TROUBLESHOOTING",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Network troubleshooting steps",
    body: "Hi, we understand you might be experiencing network troubles at {{1}}. \nYou can try these simple steps: \nStep 1: {{2}}, \nStep 2: {{3}}, \nStep 3: {{4}}. \nNeed more help? Contact: {{5}} or view details.",
    buttons: [
      { type: "URL", text: "View details", url: "https://www.example.com" },
    ],
  },
  {
    name: "operation_disruption_1",
    category: "UTILITY",
    topic: "PUBLIC_DISRUPTION",
    usecase: "OPERATION_DISRUPTION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "This is to notify you that {{1}} at our {{2}} station are halted due to {{3}}. Please avoid the area as we work to rectify. Click the URL below to see alternate {{4}} and/or {{5}} where service is available and running. Live updates on our site, available below.",
    buttons: [
      { type: "URL", text: "View Updates", url: "https://example.gov/transit-updates" },
    ],
  },
  {
    name: "operation_disruption_2",
    category: "UTILITY",
    topic: "PUBLIC_DISRUPTION",
    usecase: "OPERATION_DISRUPTION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Regular maintenance for {{1}} is scheduled for {{2}} and the station in the {{3}} area will be closed until {{4}}. Please plan to use an alternate station if you plan to travel. Click the URL below to see alternate {{5}} and/or {{6}} where service will be available and running.",
    buttons: [
      { type: "URL", text: "View Alternatives", url: "https://example.gov/transit-schedule" },
    ],
  },
  {
    name: "order_action_required_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_ACTION_NEEDED",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}}, before we can process your order {{2}}, we need to verify some information.\n\nPlease contact us at your earliest convenience.\n\nThank you.",
    buttons: [
      { type: "PHONE_NUMBER", text: "Call us", phoneNumber: "+18005551234" },
    ],
  },
  {
    name: "order_action_required_2",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_ACTION_NEEDED",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "We were unable to process your order {{1}}. \n\nPlease call us at {{2}} for next steps. ",
    buttons: [
      { type: "PHONE_NUMBER", text: "Call us", phoneNumber: "+18005551234" },
    ],
  },
  {
    name: "order_canceled_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_OR_TRANSACTION_CANCEL",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order canceled",
    body: "{{1}}, your order {{2}} has been successfully canceled. \n\nYour refund will be processed in {{3}} business days. \n\nThank you.",
    buttons: [
      { type: "URL", text: "View order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_canceled_2",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_OR_TRANSACTION_CANCEL",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "{{1}}, per your request, we have canceled your order {{2}}. \n\nYour {{3}} will be processed in {{4}} business days. \n\nYou can track this below.",
    buttons: [
      { type: "URL", text: "View order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_canceled_3",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_OR_TRANSACTION_CANCEL",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi, this is to confirm we have successfully canceled your recent order {{1}}. \n\nThank you.",
    buttons: [
      { type: "URL", text: "View order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_canceled_4",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_OR_TRANSACTION_CANCEL",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order canceled",
    body: "Hello {{1}}, \n\nYour order {{2}} has been canceled. \n\nA refund will be issued to your original payment method soon.",
    buttons: [
      { type: "URL", text: "Order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_confirm_auto_schedule",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, your {{2}} order has been successfully placed! We've scheduled an appointment for {{3}} at your preferred location. Please confirm if this time slot works for you. ",
    buttons: [
      { type: "QUICK_REPLY", text: "Confirm" },
      { type: "QUICK_REPLY", text: "Reschedule" },
    ],
  },
  {
    name: "order_confirm_manual_schedule",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, your {{2}} order is placed! Reply **Schedule** to pick a time slot for your appointment.",
    buttons: [
      { type: "QUICK_REPLY", text: "Schedule" },
    ],
  },
  {
    name: "order_confirmed",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order confirmed",
    body: "Hi {{1}}, \nWe're getting your order {{2}} ready and will let you know when it's on the way.",
  },
  {
    name: "order_delay_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_DELAY",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}}, there is a {{2}} in {{3}} your order {{4}}. \n\nWe're working to resolve it as soon as possible. \n\nWe will follow up with an update. \n\nWe apologize for any inconvenience.\nWe'll send you an updated delivery status when we can.",
    buttons: [
      { type: "URL", text: "Track my order", url: "https://www.example.com" },
      { type: "URL", text: "View order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_delay_2",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_DELAY",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Item(s) out-of-stock",
    body: "Hi {{1}}, \n\nItem(s) from your recent order {{2}} are out-of-stock. We will notify you as soon as your item(s) ship. \n\nIf you prefer not to wait, please click below to {{3}} your order. \n\nWe apologize for any inconvenience.",
    buttons: [
      { type: "URL", text: "Manage order", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_delivered",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order delivered",
    body: "Hi {{1}},\nYour {{2}} has been delivered. Thank you for shopping with us.\n",
  },
  {
    name: "order_management_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order confirmed",
    body: "Hi {{1}},\n\nThank you for your {{2}}! Your order number is {{3}}.\n\nWe'll start getting {{4}} ready to ship.\n\nEstimated delivery: {{5}} \n\nWe will let you know when your order ships.",
    buttons: [
      { type: "URL", text: "View order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_management_2",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order confirmed",
    body: "Hi {{1}}, your order is confirmed and your order number is {{2}}. \n\nEstimated delivery: {{3}}. \n\nWe will follow up with more details as we prepare your order for shipment.",
    buttons: [
      { type: "URL", text: "View order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_management_3",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order confirmed",
    body: "Hi {{1}}, we've received your order. \n\nYour order number is {{2}}. \n\nEstimated delivery: {{3}}.\n\nClick below to manage your order.",
    buttons: [
      { type: "URL", text: "Manage order", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_management_4",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order confirmed!",
    body: "Hi {{1}},\nYour order has been successfully placed and is being processed. Your order number is {{2}}. You can view order details below.",
    buttons: [
      { type: "URL", text: "View order", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_management_5",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order received",
    body: "Hello {{1}},\n\nWe received your order {{2}}. We’ll send you a status update once your payment is approved.\n\nThank you for shopping with us!",
    buttons: [
      { type: "URL", text: "Order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_management_6",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order confirmed",
    body: "Hi {{1}},\n\nYour order {{2}} has been successfully placed with {{3}} and is being processed.",
    buttons: [
      { type: "URL", text: "View order", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_management_no_cta_5",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order received",
    body: "Hello {{1}},\n\nWe received your order {{2}}. We’ll send you a status update once your payment is approved.\n\nThank you for shopping with us!",
  },
  {
    name: "order_pick_up_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_PICK_UP",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Ready for pick up!",
    body: "Hi {{1}}, your order {{2}} is ready for pick up at {{3}}.\nWhen you arrive, tap the button below and we will bring your order to you. \nSee you soon!\n",
    buttons: [
      { type: "QUICK_REPLY", text: "I've arrived" },
    ],
  },
  {
    name: "order_pick_up_3",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_PICK_UP",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Great news! Your order {{1}} is now ready for pick up at {{2}}. \n\nClick \"I'm here\" when you arrive and we will meet you with your products. \n\nSee you soon!",
    buttons: [
      { type: "QUICK_REPLY", text: "I'm here" },
    ],
  },
  {
    name: "order_pick_up_4",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_PICK_UP",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "It’s time to pick up your order",
    body: "Hello {{1}},\n\nYour order {{2}} is now ready for pickup at {{3}}.\n\nPlease remember to bring a photo ID with you.\n\nSee you soon!",
    buttons: [
      { type: "URL", text: "Order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_pick_up_no_cta_4",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_PICK_UP",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "It’s time to pick up your order",
    body: "Hello {{1}},\n\nYour order {{2}} is now ready for pickup at {{3}}.\n\nPlease remember to bring a photo ID with you.\n\nSee you soon!",
  },
  {
    name: "order_shipped",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "SHIPMENT_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order shipped",
    body: "Hi {{1}}, \nYour order {{2}} has been shipped and is on the way.\n",
  },
  {
    name: "order_update_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_UPDATE",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Your order is being prepared",
    body: "Hi {{1}},\n\nWe’re preparing your order {{2}} and will let you know when it’s ready.",
    buttons: [
      { type: "URL", text: "Order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "order_update_no_cta_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "DELIVERY_UPDATE",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Your order is being prepared",
    body: "Hi {{1}},\n\nWe’re preparing your order {{2}} and will let you know when it’s ready.",
  },
  {
    name: "payment_action_required_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_ACTION_REQUIRED",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Verify your payment info",
    body: "Hi {{1}}, \n\nPayment for your {{2}} card ending in {{3}} is coming due. \n\nVerify your information to avoid {{4}} fees.",
    footer: "Please ignore this message if you've already paid.",
    buttons: [
      { type: "URL", text: "Verify", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_action_required_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_ACTION_REQUIRED",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Review a recent transaction",
    body: "Hi {{1}},\n\nWe encountered an issue with your recent transaction for {{2}} at {{3}}. \n\nPlease contact us at {{4}} for assistance.",
    buttons: [
      { type: "PHONE_NUMBER", text: "Call us", phoneNumber: "+18005551234" },
    ],
  },
  {
    name: "payment_action_required_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_ACTION_REQUIRED",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Could not process payment",
    body: "Your scheduled payment of {{1}} for {{2}} could not be processed. \n\nPlease contact us at {{3}} for assistance.",
    buttons: [
      { type: "PHONE_NUMBER", text: "Call us", phoneNumber: "+18005551234" },
    ],
  },
  {
    name: "payment_confirmation_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_CONFIRMATION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Hi {{1}},\n\nWe have received your payment of {{2}} for {{3}}. \n\nThank you for your payment.",
    buttons: [
      { type: "URL", text: "View payment details", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_confirmation_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_CONFIRMATION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Successful payment",
    body: "Your payment of {{1}} for {{2}} has been processed successfully. \n\nWe appreciate your business.",
    buttons: [
      { type: "URL", text: "View details", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_confirmation_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_CONFIRMATION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Payment confirmation:\n\nAccount: {{1}}\nAmount: {{2}}\nDate: {{3}}\n\nThank you and have a nice day.",
    buttons: [
      { type: "URL", text: "View details", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_confirmation_4",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order approved",
    body: "Hello {{1}},\n\nYour payment of {{2}} for order {{3}} has been approved.",
    buttons: [
      { type: "URL", text: "Order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_due_reminder",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_DUE_REMINDER",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Payment due",
    body: "Hi {{1}}, your {{2}} bill of {{3}} is due on {{4}}. Pay now to avoid service disruption.",
    footer: "Ignore if already paid.",
    buttons: [
      { type: "URL", text: "Pay now", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_failed_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_REJECT_FAIL",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Hi {{1}}, your recent payment of {{2}} for your {{3}} account has failed. \n\nPlease check your account and try again.",
    buttons: [
      { type: "URL", text: "View account", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_failed_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_REJECT_FAIL",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Hi {{1}},\n\nWe were unable to process your payment of {{2}} for {{3}}. \n\nPlease update your payment method or contact us for assistance.",
    buttons: [
      { type: "URL", text: "View account", url: "https://www.example.com" },
      { type: "PHONE_NUMBER", text: "Call us", phoneNumber: "+18005551234" },
    ],
  },
  {
    name: "payment_failed_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_REJECT_FAIL",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Your payment was rejected. \n\nAccount: {{1}}\nAmount: {{2}}\nDate: {{3}}\n\nPlease check your account and try again.",
    buttons: [
      { type: "URL", text: "View account", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_failed_4",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_REJECT_FAIL",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Payment failed",
    body: "Hi {{1}}, we were unable to process your {{2}} bill payment. Please try again or contact our support team.",
    buttons: [
      { type: "URL", text: "Pay now", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_notice_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_NOTICE",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Your payment for {{1}} will be processed on {{2}}. \n\nThank you!",
  },
  {
    name: "payment_notice_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_NOTICE",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Thank you for scheduling your payment of {{1}}. \n\nWe will {{2}} on {{3}}.",
  },
  {
    name: "payment_notice_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_NOTICE",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "This is to {{1}} your payment of {{2}} for {{3}} will be processed on {{4}}.",
  },
  {
    name: "payment_overdue_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_OVERDUE",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Payment overdue",
    body: "Your {{1}} payment of {{2}} is overdue by {{3}} days. \n\nPlease pay now to avoid {{4}}. Contact us if you need assistance. ",
    buttons: [
      { type: "URL", text: "Pay now", url: "https://www.example.com" },
      { type: "PHONE_NUMBER", text: "Contact us", phoneNumber: "+18005551234" },
    ],
  },
  {
    name: "payment_overdue_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_OVERDUE",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Hi {{1}}, you have a payment overdue:\n\nAccount: {{2}}\nAmount due: {{3}}\nDue date: {{4}}\n\nUse the button below to complete payment via our website.\nPlease ignore this message if you've already paid.\n",
    footer: "Please ignore this message if you've already paid.",
    buttons: [
      { type: "URL", text: "Pay now", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_overdue_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_OVERDUE",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Payment is overdue for your {{1}} card ending in {{2}} for {{3}}. \n\nPlease click to pay now and avoid {{4}} fees.",
    buttons: [
      { type: "URL", text: "Pay now", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_recharge_reminder_01",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_DUE_REMINDER",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Hello! Your {{1}} expires in {{2}}.\nYou can top up your number {{3}} - {{4}} - with {{5}} to avoid interruptions.\n\nOr click the link below to top up with another amount of your choice.\n\nIf you have already topped up, please disregard this message. Thank you!",
    buttons: [
      { type: "ORDER_DETAILS", text: "Review and Pay" },
    ],
  },
  {
    name: "payment_reminder_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_DUE_REMINDER",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Payment due soon",
    body: "Hello {{1}}, \n\nYour payment of {{2}} is due on {{3}}.\n\nPlease ignore this message if you've already paid.\n",
    buttons: [
      { type: "URL", text: "Pay now", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_reminder_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_DUE_REMINDER",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Your payment of {{1}} is due on {{2}}. \n\nPay now to avoid {{3}}.\n\nIf you already paid, please ignore this message.",
    buttons: [
      { type: "URL", text: "Pay now", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_reminder_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_DUE_REMINDER",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Payment due",
    body: "Payment reminder:\n\nAccount: {{1}}\nAmount due: {{2}}\nDue date: {{3}}\n\nPay now to avoid {{4}}.\n\nPlease ignore this if you have already paid.",
    buttons: [
      { type: "URL", text: "Pay now", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_reminder_4",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_DUE_REMINDER",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Payment of {{1}} due",
    body: "Hi {{1}},\n\nPayment of {{2}} for your {{3}} card ending in {{4}} is due on {{5}}.\n\nPay now to avoid late fees.\nPlease ignore this message if you've already paid.\n",
    footer: "Please ignore this message if you've already paid.",
    buttons: [
      { type: "URL", text: "Pay now", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_scheduled_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_SCHEDULED",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Your payment of {{1}} for your {{2}} account is scheduled for {{3}}. \n\nPlease ensure you have sufficient funds to avoid generating any {{4}} fees.",
    buttons: [
      { type: "URL", text: "Manage payment", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_scheduled_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_SCHEDULED",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Upcoming scheduled payment",
    body: "Hi {{1}},\n\nThank you for scheduling your payment of {{2}} for your {{3}} account on {{4}}. \n\nPlease visit your account if you would like to make any changes ahead of this date.",
    buttons: [
      { type: "URL", text: "Manage payment", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_scheduled_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_SCHEDULED",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Hi {{1}}, this is to remind you of your upcoming scheduled payment: \n\nDate: {{2}}\nAccount: {{3}}\nAmount: {{4}}\n\nThank you and have a nice day.",
    buttons: [
      { type: "URL", text: "Manage payment", url: "https://www.example.com" },
    ],
  },
  {
    name: "payment_successful",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "PAYMENT_SUCCESSFUL",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Payment received",
    body: "Hi {{1}}, your {{2}} bill payment of {{3}} has been successfully received. Your payment date was {{4}}. Thank you!",
    buttons: [
      { type: "URL", text: "Receipt", url: "https://www.example.com" },
    ],
  },
  {
    name: "privacy_disclosure_1",
    category: "UTILITY",
    topic: "LEGAL_REGULATORY_COMPLIANCE",
    usecase: "PRIVACY_DISCLOSURES",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "We updated our privacy policy on {{1}}. Please click the button below to learn more.",
    buttons: [
      { type: "URL", text: "View Policy", url: "https://example.com/privacy-policy" },
    ],
  },
  {
    name: "product_recall_1",
    category: "UTILITY",
    topic: "ACCOUNT_OR_PRODUCT_PROTECTION",
    usecase: "PRODUCT_RECALLS",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "The {{1}} you ordered on {{2}} has been recalled. Please click below to let us know how you would like to proceed.",
    buttons: [
      { type: "URL", text: "View Options", url: "https://example.com/product-recall/{{1}}" },
    ],
  },
  {
    name: "purchase_receipt_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "RECEIPT_ATTACHMENT",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Thank you for your purchase of {{1}} from {{2}}. Your {{3}} PDF is attached.",
  },
  {
    name: "purchase_receipt_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "RECEIPT_ATTACHMENT",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Thank you for using your {{1}} card at {{2}}. Your {{3}} is attached as a PDF.",
  },
  {
    name: "purchase_receipt_3",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "RECEIPT_ATTACHMENT",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hello {{1}},\n\nYour invoice for order {{2}} is attached.\n\nThank you for shopping with us!",
    buttons: [
      { type: "URL", text: "Order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "purchase_transaction_alert",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "TRANSACTION_ALERT",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "This message is to confirm your {{1}} for {{2}} from {{3}} on {{4}}.",
  },
  {
    name: "recharge_failure",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "RECHARGE_REJECT_FAIL",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Recharge failed",
    body: "Hi {{1}}, we were unable to process your mobile recharge. Please try again or contact our support team.",
    buttons: [
      { type: "URL", text: "Recharge", url: "https://www.example.com" },
    ],
  },
  {
    name: "recharge_reminder",
    category: "UTILITY",
    topic: "ACCOUNT_UPDATES",
    usecase: "RENEWAL_REMINDER",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Pack expiry reminder",
    body: "Hi {{1}}, your {{2}} is ending tonight. To continue using without interruption, please recharge.",
    buttons: [
      { type: "URL", text: "Recharge", url: "https://www.example.com" },
    ],
  },
  {
    name: "recharge_successful",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "RECHARGE_CONFIRMATION",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Recharge successful",
    body: "Hi {{1}}, your mobile recharge of {{2}} has been successful! Your new balance is {{3}}. ",
  },
  {
    name: "refund_confirmation_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_REFUND",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "You were refunded for {{1}}",
    body: "Hi {{1}},\n\nYour refund for {{2}} has been processed for order {{3}}. You'll be credited back to your original payment method in 3-5 business days.",
  },
  {
    name: "renewal_reminder",
    category: "UTILITY",
    topic: "ACCOUNT_UPDATES",
    usecase: "RENEWAL_REMINDER",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Service renewal reminder",
    body: "Your {{1}} plan is scheduled to renew on {{2}}. Please maintain sufficient balance to keep the service active.",
  },
  {
    name: "renewal_successful",
    category: "UTILITY",
    topic: "ACCOUNT_UPDATES",
    usecase: "RENEWAL_CONFIRMATION",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, \n\nYour {{2}} plan has been successfully renewed. \nYour new plan details are: \n\nPlan name: {{3}} \nData limit: {{4}} \nValidity: {{5}}\n\nThank you for choosing us!",
  },
  {
    name: "request_contact_info_1",
    category: "UTILITY",
    topic: "CONTACT_REQUEST",
    usecase: "PHONE_NUMBER_REQUEST",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES", "TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, we'd like to have your phone number on file so we can reach you more easily. Please share your contact info below.",
    buttons: [
      { type: "REQUEST_CONTACT_INFO", text: "Share Contact Info" },
    ],
  },
  {
    name: "request_contact_info_2",
    category: "UTILITY",
    topic: "CONTACT_REQUEST",
    usecase: "PHONE_NUMBER_REQUEST",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES", "TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, please share your phone number with us so we can stay in touch and assist you better.",
    buttons: [
      { type: "REQUEST_CONTACT_INFO", text: "Share Contact Info" },
    ],
  },
  {
    name: "request_contact_info_3",
    category: "UTILITY",
    topic: "CONTACT_REQUEST",
    usecase: "PHONE_NUMBER_REQUEST",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES", "TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, having your phone number helps us serve you faster. Tap below to share your contact info.",
    buttons: [
      { type: "REQUEST_CONTACT_INFO", text: "Share Contact Info" },
    ],
  },
  {
    name: "rescheduling_request",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "RESCHEDULEING_REQUEST",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, we need to reschedule your {{2}}. Reply **Reschedule** to pick a new time.",
    buttons: [
      { type: "QUICK_REPLY", text: "Reschedule" },
    ],
  },
  {
    name: "return_confirmation_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "RETURN_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}}, thank you for returning product(s) from your order {{2}}. \n\nWe are currently processing your return and will notify you of your {{3}} status.",
    buttons: [
      { type: "URL", text: "Manage order", url: "https://www.example.com" },
    ],
  },
  {
    name: "return_confirmation_2",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "RETURN_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Return received",
    body: "We have received item(s) from your order {{1}}. \n\nYour return is complete, and we have processed your {{2}} for {{3}}. \n\nThank you for your business.",
    buttons: [
      { type: "URL", text: "Manage order", url: "https://www.example.com" },
    ],
  },
  {
    name: "roaming_reminder",
    category: "UTILITY",
    topic: "ACCOUNT_UPDATES",
    usecase: "ROAMING_REMINDER",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Roaming cost advisory",
    body: "Hi {{1}}, your number is currently on a network outside {{2}}. To avoid high pay-as-you-go charges, you can activate an international roaming pack.",
    buttons: [
      { type: "URL", text: "Activate", url: "https://www.example.com" },
    ],
  },
  {
    name: "service_disruption",
    category: "UTILITY",
    topic: "ACCOUNT_UPDATES",
    usecase: "SERVICE_DISRUPTION",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Dear Customer, we have scheduled network updates on {{1}} between {{2}} and {{3}}. You may experience temporary service disruption. Thank you for your understanding.",
  },
  {
    name: "severe_weather_alert_1",
    category: "UTILITY",
    topic: "PUBLIC_SAFETY",
    usecase: "SEVERE_WEATHER",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "There is a {{1}} alert in the {{2}} area. We recommend you remain indoors until {{3}}. If you are facing issues related to {{4}} or {{5}}, you can inform us by using the button below and we will follow up for an on-site inspection. We will follow up with key updates and any recommended precautions. For more information on {{6}} preparedness, click the URL below.",
    buttons: [
      { type: "URL", text: "Learn More", url: "https://example.gov/preparedness/{{1}}" },
    ],
  },
  {
    name: "severe_weather_alert_2",
    category: "UTILITY",
    topic: "PUBLIC_SAFETY",
    usecase: "SEVERE_WEATHER",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "There is a {{1}} alert in the {{2}} area. For more information on precautions to take during a {{3}} click the URL below. For live updates on the {{4}} alert in the {{5}} area, visit our website {{6}}.",
    buttons: [
      { type: "URL", text: "View Precautions", url: "https://example.gov/precautions/{{1}}" },
    ],
  },
  {
    name: "shifting_journey",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "ORDER_CONFIRMATION",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, your broadband connection shifting request is being processed! We'll keep you updated on the status.",
    buttons: [
      { type: "URL", text: "Track Status", url: "https://www.example.com" },
    ],
  },
  {
    name: "shipment_confirmation_1",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "SHIPMENT_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order shipped",
    body: "Hi {{1}}, your order has shipped! \n\nYour tracking number is {{2}}. \n\nEstimated delivery is {{3}}.",
    footer: "We will continue to provide updates on this shipment until it is delivered.",
    buttons: [
      { type: "URL", text: "Track shipment", url: "https://www.example.com" },
    ],
  },
  {
    name: "shipment_confirmation_2",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "SHIPMENT_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}}, great news! Your order {{2}} has shipped.\n\nTracking #: {{3}}\nEstimated delivery: {{4}}\n\nWe will provide updates until delivery.",
    buttons: [
      { type: "URL", text: "Track shipment", url: "https://www.example.com" },
    ],
  },
  {
    name: "shipment_confirmation_3",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "SHIPMENT_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    body: "Hi {{1}}, your order {{2}} has left our {{3}} and is on its way to you! \n\nYour tracking ID is {{4}}. \n\nClick below to track your package.",
    buttons: [
      { type: "URL", text: "Track my order", url: "https://www.example.com" },
    ],
  },
  {
    name: "shipment_confirmation_4",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "SHIPMENT_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Your order is en route!",
    body: "Hi {{1}},\n\nWe're happy to inform you that your order {{2}} has shipped! Click view order details to view the status of your shipment.",
    buttons: [
      { type: "URL", text: "View order details", url: "https://www.example.com" },
    ],
  },
  {
    name: "shipment_confirmation_5",
    category: "UTILITY",
    topic: "ORDER_MANAGEMENT",
    usecase: "SHIPMENT_CONFIRMATION",
    industries: ["E_COMMERCE"],
    language: "en_US",
    header: "Order shipped",
    body: "Hi {{1}},\n\nWe’re happy to inform you that your order {{2}} has shipped! Click below to view the status of your shipment.",
    buttons: [
      { type: "URL", text: "View order", url: "https://www.example.com" },
    ],
  },
  {
    name: "statement_available_1",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "STATEMENT_AVAILABLE",
    industries: ["E_COMMERCE", "FINANCIAL_SERVICES"],
    language: "en_US",
    header: "Statement available",
    body: "Hi {{1}}, \n\nYour {{2}} statement for your account ending in {{3}} is now available. \n\nClick below to see your statement. ",
    buttons: [
      { type: "URL", text: "View statement", url: "https://www.example.com" },
    ],
  },
  {
    name: "statement_available_2",
    category: "UTILITY",
    topic: "PAYMENTS",
    usecase: "STATEMENT_AVAILABLE",
    industries: ["FINANCIAL_SERVICES", "E_COMMERCE"],
    language: "en_US",
    header: "Statement available",
    body: "This is to notify you that your latest statement for your {{1}} account is now available. \n\nPlease log into your account to view your statement.",
    buttons: [
      { type: "URL", text: "View statement", url: "https://www.example.com" },
    ],
  },
  {
    name: "support_ticket_acknowledgement",
    category: "UTILITY",
    topic: "CUSTOMER_FEEDBACK",
    usecase: "TICKET_ACKNOWLEDGEMENT",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Your request {{1}} is registered. We will contact you within {{2}} hours.",
  },
  {
    name: "system_outage_1",
    category: "UTILITY",
    topic: "PUBLIC_DISRUPTION",
    usecase: "SYSTEM_OUTAGES",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "We have detected a system outage that impacts zip code {{1}}. We expect to restore service by {{2}}. We apologize for the inconvenience.",
  },
  {
    name: "system_outage_2",
    category: "UTILITY",
    topic: "PUBLIC_DISRUPTION",
    usecase: "SYSTEM_OUTAGES",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "The system outage has been restored for zip code {{1}}. If you are still experiencing an outage in zip code {{2}}, click the button below to alert us.",
    buttons: [
      { type: "QUICK_REPLY", text: "Report Outage" },
    ],
  },
  {
    name: "technician_arrival",
    category: "UTILITY",
    topic: "EVENT_REMINDER",
    usecase: "TECHNICIAN_ARRIVAL",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    body: "Hi {{1}}, our technician will arrive at your location within the next {{2}}. Tap to track real-time location.",
    buttons: [
      { type: "URL", text: "Track Location", url: "https://www.example.com" },
    ],
  },
  {
    name: "upgrade_confirmation",
    category: "UTILITY",
    topic: "ACCOUNT_UPDATES",
    usecase: "UPGRADE_CONFIRMATION",
    industries: ["TELECOMMUNICATION"],
    language: "en_US",
    header: "Speed-upgrade notice",
    body: "We are pleased to inform you that your internet speed has been upgraded to {{1}} Mbps. Thank you for choosing our services.",
  },
  {
    name: "voting_registration_1",
    category: "UTILITY",
    topic: "PUBLIC_SERVICE",
    usecase: "VOTING_REGISTRATION",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "To vote on {{1}}, please ensure your voter {{2}} is active. Please click the URL below to understand steps required to renew, if needed.",
    buttons: [
      { type: "URL", text: "Check Registration", url: "https://example.gov/voter-registration" },
    ],
  },
  {
    name: "warranty_alert_1",
    category: "UTILITY",
    topic: "ACCOUNT_OR_PRODUCT_PROTECTION",
    usecase: "WARRANTY_ALERTS",
    industries: ["FINANCIAL_SERVICES"],
    language: "en_US",
    body: "Thank you for your purchase of {{1}}. Your warranty is active as of {{2}}. Our {{3}} are below, for your reference.",
  },
]
